# Install the Codex bridge on native Windows PowerShell. Idempotent; refuses to overwrite anything.
#
#     .\.claude\codex\install.ps1
#
# Uses HARD LINKS for files and a DIRECTORY JUNCTION for the wrappers: a Windows symlink needs
# Developer Mode or an elevated prompt, and failing on that would make the bridge unavailable to
# exactly the people who cannot enable it.
#
# Re-run it if the same checkout moves between WSL and native Windows: the two create different
# link types and only one is meaningful to the environment launching Codex.

$ErrorActionPreference = 'Stop'

$Bridge     = Split-Path -Parent $MyInvocation.MyCommand.Path
$ClaudeDir  = Split-Path -Parent $Bridge
$ProjectDir = Split-Path -Parent $ClaudeDir

Push-Location $ProjectDir
try {
    $gitDir = (git rev-parse --absolute-git-dir 2>$null)
    if (-not $gitDir) { throw "Refusing to install outside a git working tree: $ProjectDir" }

    $exclude = Join-Path $gitDir 'info/exclude'
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $exclude) | Out-Null
    if (-not (Test-Path $exclude)) { New-Item -ItemType File -Path $exclude | Out-Null }
    $current = Get-Content $exclude -ErrorAction SilentlyContinue
    foreach ($entry in @('/AGENTS.md', '/.agents/', '/.codex/')) {
        if ($current -notcontains $entry) { Add-Content -Path $exclude -Value $entry }
    }

    # Wrappers are generated by the bash script where bash exists; regenerate by hand otherwise.
    if (Get-Command bash -ErrorAction SilentlyContinue) {
        bash "$Bridge/generate_wrappers.sh"
    } else {
        Write-Host "  note     bash not found; wrappers not regenerated (check_bridge will say if they are stale)"
    }

    function New-BridgeLink {
        param($Path, $Target, $Kind)
        if (Test-Path $Path) {
            $item = Get-Item $Path -Force
            if ($item.LinkType) { Write-Host "  ok       $Path (already linked)"; return }
            throw "Refusing to replace an existing path: $Path"
        }
        New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
        New-Item -ItemType $Kind -Path $Path -Target $Target | Out-Null
        Write-Host "  linked   $Path"
    }

    New-BridgeLink -Path (Join-Path $ProjectDir 'AGENTS.md') `
                   -Target (Join-Path $Bridge 'AGENTS.md') -Kind HardLink
    New-BridgeLink -Path (Join-Path $ProjectDir '.agents/skills') `
                   -Target (Join-Path $Bridge 'skills') -Kind Junction
    New-BridgeLink -Path (Join-Path $ProjectDir '.codex/hooks.json') `
                   -Target (Join-Path $Bridge 'hooks.json') -Kind HardLink

    if (Get-Command bash -ErrorAction SilentlyContinue) { bash "$Bridge/check_bridge.sh" }
    Write-Host "Codex bridge installed. Restart Codex, then review and trust the project hooks with /hooks."
}
finally { Pop-Location }
